# Generated by Django 3.0.7 on 2023-08-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20230812_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('A', 'Advanced'), ('B', 'Basic'), ('I', 'Intermediate')], default='B', max_length=1),
        ),
    ]
