# Generated by Django 3.0.7 on 2023-08-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20230812_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('B', 'Basic'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='period',
            field=models.CharField(choices=[('N', 'Nocturnal'), ('V', 'Vespertine'), ('M', 'Matutinal')], default='M', max_length=1),
        ),
    ]
