# Generated by Django 3.0.7 on 2023-08-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20230812_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('I', 'Intermediate'), ('A', 'Advanced'), ('B', 'Basic')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='period',
            field=models.CharField(choices=[('M', 'Matutinal'), ('N', 'Nocturnal'), ('V', 'Vespertine')], default='M', max_length=1),
        ),
    ]
